//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TemplateStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.TemplateStrings", typeof(TemplateStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this site.
        /// </summary>
        public static string tmpl_about_site {
            get {
                return ResourceManager.GetString("tmpl-about-site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified:.
        /// </summary>
        public static string tmpl_date_mod {
            get {
                return ResourceManager.GetString("tmpl-date-mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Canada footer.
        /// </summary>
        public static string tmpl_gc_foot {
            get {
                return ResourceManager.GetString("tmpl-gc-foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Canada.
        /// </summary>
        public static string tmpl_gc_sig {
            get {
                return ResourceManager.GetString("tmpl-gc-sig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol of the Government of Canada.
        /// </summary>
        public static string tmpl_gc_wmms {
            get {
                return ResourceManager.GetString("tmpl-gc-wmms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selection.
        /// </summary>
        public static string tmpl_lang_select {
            get {
                return ResourceManager.GetString("tmpl-lang-select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string tmpl_search {
            get {
                return ResourceManager.GetString("tmpl-search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search website.
        /// </summary>
        public static string tmpl_search_site {
            get {
                return ResourceManager.GetString("tmpl-search-site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary menu.
        /// </summary>
        public static string tmpl_sec_menu {
            get {
                return ResourceManager.GetString("tmpl-sec-menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section menu.
        /// </summary>
        public static string tmpl_section_menu {
            get {
                return ResourceManager.GetString("tmpl-section-menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to &quot;About this site&quot;.
        /// </summary>
        public static string tmpl_skip_about_site {
            get {
                return ResourceManager.GetString("tmpl-skip-about-site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to main content.
        /// </summary>
        public static string tmpl_skip_cont {
            get {
                return ResourceManager.GetString("tmpl-skip-cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to section menu.
        /// </summary>
        public static string tmpl_skip_section {
            get {
                return ResourceManager.GetString("tmpl-skip-section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string tmpl_terms {
            get {
                return ResourceManager.GetString("tmpl-terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions of use.
        /// </summary>
        public static string tmpl_terms_of_use {
            get {
                return ResourceManager.GetString("tmpl-terms-of-use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics menu.
        /// </summary>
        public static string tmpl_topics_menu {
            get {
                return ResourceManager.GetString("tmpl-topics-menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        public static string tmpl_transparency {
            get {
                return ResourceManager.GetString("tmpl-transparency", resourceCulture);
            }
        }
    }
}
