//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GCWU_FEGC {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GCWU_FEGC() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GCWU_FEGC", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string hlkLangSwitch {
            get {
                return ResourceManager.GetString("hlkLangSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to content.
        /// </summary>
        internal static string hlSkipContent {
            get {
                return ResourceManager.GetString("hlSkipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to footer.
        /// </summary>
        internal static string hlSkipFooter {
            get {
                return ResourceManager.GetString("hlSkipFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;gcwu-sig-eng&quot; title=&quot;Government of Canada&quot;&gt;&lt;img src=&quot;/theme/theme-gcwu-fegc/images/sig-eng.gif&quot; width=&quot;214&quot; height=&quot;20&quot; alt=&quot;Government of Canada&quot; /&gt;&lt;/div&gt;.
        /// </summary>
        internal static string ltlDivSig {
            get {
                return ResourceManager.GetString("ltlDivSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Canada navigation bar.
        /// </summary>
        internal static string ltlGoCBarHead {
            get {
                return ResourceManager.GetString("ltlGoCBarHead", resourceCulture);
            }
        }
    }
}
