//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GCWU_FEGC {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GCWU_FEGC() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GCWU_FEGC", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breadcrumb trail.
        /// </summary>
        internal static string BC {
            get {
                return ResourceManager.GetString("BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSrch {
            get {
                return ResourceManager.GetString("btnSrch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.gc.ca.
        /// </summary>
        internal static string CanadagcTxt {
            get {
                return ResourceManager.GetString("CanadagcTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.canada.gc.ca/menu-eng.html.
        /// </summary>
        internal static string CanadagcUrl {
            get {
                return ResourceManager.GetString("CanadagcUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.gc.ca.
        /// </summary>
        internal static string CDNLinkText {
            get {
                return ResourceManager.GetString("CDNLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.canada.gc.ca/menu-eng.html.
        /// </summary>
        internal static string CDNLinkUrl {
            get {
                return ResourceManager.GetString("CDNLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string DeptText {
            get {
                return ResourceManager.GetString("DeptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.canada.gc.ca/aboutgov-ausujetgouv/depts/menu-eng.html.
        /// </summary>
        internal static string DeptUrl {
            get {
                return ResourceManager.GetString("DeptUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Economy&lt;/span&gt;&lt;br /&gt;plandaction.gc.ca.
        /// </summary>
        internal static string EconomyTxt {
            get {
                return ResourceManager.GetString("EconomyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://actionplan.gc.ca.
        /// </summary>
        internal static string EconomyURL {
            get {
                return ResourceManager.GetString("EconomyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Service Canada&lt;/span&gt;&lt;br /&gt;servicecanada.gc.ca.
        /// </summary>
        internal static string EmploieTxt {
            get {
                return ResourceManager.GetString("EmploieTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.servicecanada.gc.ca/fra/accueil.shtml.
        /// </summary>
        internal static string EmploieURL {
            get {
                return ResourceManager.GetString("EmploieURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer / &lt;span lang=&quot;fr&quot;&gt;Pied de page&lt;/span&gt;.
        /// </summary>
        internal static string FooterHead {
            get {
                return ResourceManager.GetString("FooterHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        internal static string FooterTxt {
            get {
                return ResourceManager.GetString("FooterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Canada footer.
        /// </summary>
        internal static string GoCFootertxt {
            get {
                return ResourceManager.GetString("GoCFootertxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Health&lt;/span&gt;&lt;br /&gt;healthycanadians.gc.ca.
        /// </summary>
        internal static string HealthyCanTxt {
            get {
                return ResourceManager.GetString("HealthyCanTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://healthycanadians.gc.ca/index-eng.php.
        /// </summary>
        internal static string HealthyCanURL {
            get {
                return ResourceManager.GetString("HealthyCanURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string hlkLangSwitch {
            get {
                return ResourceManager.GetString("hlkLangSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to content.
        /// </summary>
        internal static string hlSkipContent {
            get {
                return ResourceManager.GetString("hlSkipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to footer.
        /// </summary>
        internal static string hlSkipFooter {
            get {
                return ResourceManager.GetString("hlSkipFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta name=&apos;dcterms.language&apos; title=&apos;ISO639-2&apos; content=&apos;eng&apos;&gt;.
        /// </summary>
        internal static string LangMeta {
            get {
                return ResourceManager.GetString("LangMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selection links / &lt;span lang=&quot;fr&quot;&gt;Liens de sélection de langue&lt;/span&gt;.
        /// </summary>
        internal static string LangSelecLinksHead {
            get {
                return ResourceManager.GetString("LangSelecLinksHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;gcwu-sig-eng&quot; title=&quot;Government of Canada&quot;&gt;&lt;img src=&quot;/theme/theme-gcwu-fegc/images/sig-eng.gif&quot; width=&quot;214&quot; height=&quot;20&quot; alt=&quot;Government of Canada&quot; /&gt;&lt;/div&gt;.
        /// </summary>
        internal static string ltlDivSig {
            get {
                return ResourceManager.GetString("ltlDivSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Canada navigation bar.
        /// </summary>
        internal static string ltlGoCBarHead {
            get {
                return ResourceManager.GetString("ltlGoCBarHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;mb-menu&quot; data-ajax-replace=&quot;/Includes/menu-eng.txt&quot;&gt;.
        /// </summary>
        internal static string MenuInclude {
            get {
                return ResourceManager.GetString("MenuInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary menu.
        /// </summary>
        internal static string SecondaryNav {
            get {
                return ResourceManager.GetString("SecondaryNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Service Canada&lt;/span&gt;&lt;br /&gt;servicecanada.gc.ca.
        /// </summary>
        internal static string ServCanTxt {
            get {
                return ResourceManager.GetString("ServCanTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.servicecanada.gc.ca/eng/home.shtml.
        /// </summary>
        internal static string ServCanURL {
            get {
                return ResourceManager.GetString("ServCanURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ServiceText {
            get {
                return ResourceManager.GetString("ServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.servicecanada.gc.ca/eng/home.shtml.
        /// </summary>
        internal static string ServiceUrl {
            get {
                return ResourceManager.GetString("ServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site footer.
        /// </summary>
        internal static string SitefooterTxt {
            get {
                return ResourceManager.GetString("SitefooterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Site &lt;/span&gt;menu.
        /// </summary>
        internal static string SiteMenuHeader {
            get {
                return ResourceManager.GetString("SiteMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Experience Toolkit (WET).
        /// </summary>
        internal static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;gcwu-sig-eng&quot; title=&quot;Government of Canada / Gouvernement du Canada&quot;&gt;&lt;img src=&quot;/theme/theme-gcwu-fegc/images/sig-eng.gif&quot; class=&quot;image-actual&quot; width=&quot;214&quot; height=&quot;20&quot; alt=&quot;Government of Canada / Gouvernement du Canada&quot; /&gt;&lt;/div&gt;.
        /// </summary>
        internal static string SplashSIG {
            get {
                return ResourceManager.GetString("SplashSIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to main content / &lt;span lang=&quot;fr&quot;&gt;Passer au contenu principal&lt;/span&gt;.
        /// </summary>
        internal static string SplashSkipContent {
            get {
                return ResourceManager.GetString("SplashSkipContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to footer / &lt;span lang=&quot;fr&quot;&gt;Passer au pied de page&lt;/span&gt;.
        /// </summary>
        internal static string SplashSkipFooter {
            get {
                return ResourceManager.GetString("SplashSkipFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SrchHead {
            get {
                return ResourceManager.GetString("SrchHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search website.
        /// </summary>
        internal static string Srchlbl {
            get {
                return ResourceManager.GetString("Srchlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        internal static string TCText {
            get {
                return ResourceManager.GetString("TCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        internal static string TransparencyTxt {
            get {
                return ResourceManager.GetString("TransparencyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Travel&lt;/span&gt;&lt;br /&gt;travel.gc.ca.
        /// </summary>
        internal static string TravelTxt {
            get {
                return ResourceManager.GetString("TravelTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://travel.gc.ca/index-eng.asp.
        /// </summary>
        internal static string TravelURL {
            get {
                return ResourceManager.GetString("TravelURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol of the Government of Canada / Symbole du gouvernement du Canada.
        /// </summary>
        internal static string WMMSAlt {
            get {
                return ResourceManager.GetString("WMMSAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;gcwu-wmms-fip&quot; title=&quot;Symbol of the Government of Canada&quot;&gt;.
        /// </summary>
        internal static string wmmsDivTxt {
            get {
                return ResourceManager.GetString("wmmsDivTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol of the Government of Canada.
        /// </summary>
        internal static string wmmsTxt {
            get {
                return ResourceManager.GetString("wmmsTxt", resourceCulture);
            }
        }
    }
}
